export const coursesCards = [
  {
    testId: 1,
    name: 'Alexa',
    authorImg: 'images/courses/alexa/ava.png',
    courseImg: 'images/courses/alexa/cover.png',
    title: 'Take exam in Mathematics at 100 points',
    lessons: 12,
    tasks: 12,
    minutes: 30,
    progress: 12,
  },
  {
    testId: 2,
    name: 'Kathryn Nguyen',
    authorImg: 'images/courses/kathryn_nguyen/ava.png',
    courseImg: 'images/courses/kathryn_nguyen/cover.png',
    title: 'How buy new clothes without money in USA',
    lessons: 12,
    tasks: 12,
    minutes: 30,
    progress: 12,
  },
  {
    testId: 3,
    name: 'Diane Miles',
    authorImg: 'images/courses/diane_miles/ava.png',
    courseImg: 'images/courses/diane_miles/cover.png',
    title: 'Why people hate me?',
    lessons: 12,
    tasks: 12,
    minutes: 30,
    progress: 12,
  },
];
